{% set name = "sphinx-js" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6dd8e79c5ad09fef389af5021d7a672066f6e12a51130497f6c611544d62734b
  - folder: src
    url: https://github.com/mozilla/{{ name }}/archive/{{ version }}.tar.gz
    sha256: b70a405a16d43d688d504ec64f78bb1b4631b9c0b11e2145511206a7b2dac41e

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - docutils
    - jinja2 >=2.0,<3.0
    # TODO: should be pinned, needs historical version
    # - parsimonious >=0.7.0,<0.8.0
    - parsimonious
    - python >=3.6
    - six >=1.9.0,<2.0
    - sphinx >=3.0.0
    - nodejs

test:
  requires:
    - pytest
    - python >=3.6
    - recommonmark
    - sphinx
    # - pip
  source_files:
    - src/tests
  imports:
    - sphinx_js
  # TODO: can't be pip checked because parsimonious
  # commands:
  # - python -m pip check

about:
  home: https://github.com/mozilla/sphinx-js
  license: MIT
  license_family: MIT
  license_file: src/LICENSE
  summary: Autodoc-style extraction into Sphinx for your JS project

  description: |
    When you write a JavaScript library, how do you explain it to people? If
    it's a small project in a domain your users are familiar with, JSDoc's
    alphabetical list of routines might suffice. But in a larger project, it is
    useful to intersperse prose with your API docs without having to copy and
    paste things.

    sphinx-js lets you use the industry-leading Sphinx documentation tool with
    JS projects. It provides a handful of directives, patterned after the
    Python-centric autodoc ones, for pulling JSDoc-formatted documentation into
    reStructuredText pages. And, because you can keep using JSDoc in your code,
    you remain compatible with the rest of your JS tooling, like Google's
    Closure Compiler.

extra:
  recipe-maintainers:
    - bollwyvl
